### ISSUE TITLE
Visualization with Paraview

### ISSUE THREAD

**Issue by PetrKryslUCSD** [byuflowlab/GXBeam.jl#12]
I note that you selected lines for visualizing the deforming beams. Unfortunately, that is just one piece of the information, the other being the orientations of the cross-sections. Are there any plans of including those, perhaps with glyphs?
I admit I looked into that but didn't get too far... \_O_/

**Comment by taylormcd** [comment]
The local beam x, y, and z axis vectors (in the global frame) are output as field data so that information can be visualized with glyphs, even though I didn't visualize them in the examples.

**Comment by PetrKryslUCSD** [comment]
Nice.
