### ISSUE TITLE
Literature review

### ISSUE THREAD

**Issue by PetrKryslUCSD** [byuflowlab/GXBeam.jl#50]
I think it would be worthwhile to mention that geometrically exact beam theory has been dealt with in many more publications than are listed in the introduction. For instance, Simo et al., Betsch et al., ... It is a big topic.

**Comment by taylormcd** [comment]
I updated the literature review with more references.  Let me know if what I've added is good enough, or whether you'd like to see more.

**Comment by PetrKryslUCSD** [comment]
That is great. On another note: I notice that your *paper* does not list the limitations; your READ ME does, which is good. It just needs to make it into the paper as well. The statement of need would be a good place for it.
