### ISSUE TITLE
pointmass is less stable than mass

### ISSUE THREAD

**Issue by RibeiroAndre** [byuflowlab/GXBeam.jl#76]
Hi, Taylor.
Your fix for `time_domain_analysis` using the new `pointmass` (#71) seems to work at first, but I started running some cases and I noticed it is much more unstable than using `mass`.
It will be hard for me to give you a MWE because for simple cases it works. However, when running FSI on a flexible wing with `pointmass`, the solver diverges (or, more accurately, fails to converge) once the deflections become large, even if I reduce the timestep a lot. When I switch to `mass`, the solver is very stable again.
Both approaches give me quite similar results with `eigenvalue_analysis`, so I don't *think* it's a setup issue. Also the deflections look very similar with `time_domain_analysis`, before the solver diverges.
I'd rather use the `pointmass` approach, as I have lumped mass info for my model and that is slightly more accurate than using `mass`. But if this is very hard to fix, then I'll stick to `mass`.
Let me know if there's something I can do on my end to diagnose what is going on. I can compare the two cases at the point where one diverges and provide you with whatever info can be useful.
Thanks a lot!

**Comment by taylormcd** [comment]
My best guess is that using zero length elements increased the index of the DAE from 1 to 2, resulting in the introduction of instabilities.  I would need to confirm this.  Unfortunately, the solution for that problem would be to reduce the index of the DAE by differentiating the governing equations.

**Comment by taylormcd** [comment]
I think this is effectively resolved, since zero length elements are no longer necessary in order to model point masses.
