### ISSUE TITLE
Bug when layup does not include webs

### ISSUE THREAD

**Issue by tylercritchfield** [byuflowlab/GXBeam.jl#88]
Perhaps I'm defining my "webs" wrong in this case, but if I try using the following inputs
    `webs = []`
    `webloc = []`

this leads to the `TF` type in line 673 of section.jl to be `Any`, which throws off calculations later on. That type changes from `Float64` to `Any` in line 851 of afmesh.jl, when calling the `addwebs` method.

**Comment by taylormcd** [comment]
`web = []` is of type Vector{Any} so that's not surprising.  We should probably make it so this doesn't throw off later calculations though.
