### ISSUE TITLE
Load ramping

### ISSUE THREAD

**Issue by ss1870** [byuflowlab/GXBeam.jl#93]
Hi, just wondered if you've considered a load ramping method for the nonlinear solve? I'm wondering if it would make the solve more robust, and could it potentially result in convergence with fewer iterations?

**Comment by taylormcd** [comment]
This is already implemented. See the `time` keyword argument under https://flow.byu.edu/GXBeam.jl/dev/reference/reference/#GXBeam.static_analysis
